# Generated by Django 4.1.7 on 2023-02-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='name',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='rank',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='coin',
            name='symbol',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coin',
            name='supply',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
