# Generated by Django 4.1.7 on 2023-02-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_coin_name_coin_rank_coin_symbol_alter_coin_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='identifier',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coin',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
